#!/bin/sh
# proj-klient
# Skrypt ułatwiający oglądanie ekranu udostępnionego w aplikacji projector

SERVER=m1
PORT=8080
BASE_URL="https://$SERVER:$PORT"

# START

ROOMS_URL="$BASE_URL/room/get"

room=$(curl -sfk $ROOMS_URL)

url="$BASE_URL/?id=$room"

echo "$url" >&2

chromium --ignore-certificate-errors -new-tab $url >/dev/null 2>&1 &

exit
