#!/bin/sh
# proj-start
# Uruchamia serwer laplace i otwiera w przeglądarce stronę do udostępniania,
# parviaij 2023

SERVER=m1
PORT=8080			
URL="https://$SERVER:$PORT/?stream=1"

# START

sudo systemctl start projector  

warn -M 'Proszę kliknąć guzik "Start stream" i wybrać udostępniane okno'

chromium --ignore-certificate-errors -new-tab "$URL" >/dev/null 2>&1 &

exit
